# Generated by Django 3.2.5 on 2021-07-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(default=None),
        ),
    ]
