# Generated by Django 3.2.5 on 2021-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_alter_alias_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
